FROM node:20-alpine

# Install necessary packages
RUN apk add --no-cache ca-certificates dumb-init

# Create application directory
RUN mkdir -p /opt/app
WORKDIR /opt/app

# Copy necessary files
COPY .npmrc .
COPY package.json .
COPY package-lock.json .
COPY patches patches
COPY queries queries

# Install production dependencies
RUN npm install --only=prod

# Copy build artifacts
COPY build .

# Change ownership to the node user
RUN chown -R node:node /opt/app

# Switch to the node user
USER node

# Set the command to run the application
CMD ["dumb-init", "node", "bin/cli", "api"]
